name: datadog
namespace: monitoring

deployment:
  enabled: true
  image:
    name: datadog/agent
    tag: latest
  restartPolicy: Always
  kind: Deployment
  deployAnnotations:
    checksum/deploy_annotate: asdfasdfasdf
  podAnnotations:
    checksum/pod_annotate: asdfasdfasdf
  labels:
    app: datadog
  livenessProbe:
    failureThreshold: 6
    httpGet:
      path: /health
      port: 5555
      scheme: HTTP
    initialDelaySeconds: 15
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 5
  readinessProbe:
    failureThreshold: 6
    httpGet:
      path: /health
      port: 5555
      scheme: HTTP
    initialDelaySeconds: 15
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 5
  ports:
  - containerPort: 8125
    hostPort: 8125
    name: dogstatsdport
    protocol: UDP
  resources:
    requests:
      cpu: 750m
      memory: 200m
    limits:
      cpu: 3G
      memory: 1G
  volumeMounts:
  - mountPath: /var/run/docker.sock
    name: runtimesocket
    readOnly: true
  volumes:
  - name: runtimesocket
    hostPath:
    path: /var/run/docker.sock
    type: ""
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%

service:
  annotations:
    this_is: an_annotation
  type: ClusterIP
  ports:
    name: dogstatsdport
    port: 8125
    protocol: TCP
    targetPort: 8125

secrets:
  the_password_is: nipples

configmaps:
- name: number-1-configmap-na
  data:
    key-1: |-
      This is a whole lot of data
      that can be translated to a configmap
    key-2: |-
      This is some other stuff
- name: number-2-configmap-na
  data:
    key-1: |-
      This is a whole lot of data
      that can be translated to a configmap
    key-2: |-
      This is some other stuff
