
name: template
namespace: monitoring

deployment:
  deployments:
    deploymentOne:
      name: template-test
      hpa:
        minReplicas: 1
        maxReplicas: 10
        targetCpuUtilization: 125
      args:
      - streamer -stream_type=twitterv1
      command:
      - /bin/bash
      - -c
      resources:
        requests:
          cpu: 750m
          memory: 200m
        limits:
          cpu: 3G
          memory: 1G
  image:
    name: datadog/agent
    tag: latest
  restartPolicy: Always
  kind: Deployment
  deployAnnotations:
    checksum/deploy_annotate: asdfasdfasdf
  podAnnotations:
    checksum/pod_annotate: asdfasdfasdf
  labels: {}
  livenessProbe:
    httpGet:
      path: /health
      port: 5555
      scheme: HTTP
    periodSeconds: 15
    timeoutSeconds: 5
  readinessProbe:
    failureThreshold: 6
    httpGet:
      path: /health
      port: 5555
      scheme: HTTP
    initialDelaySeconds: 15
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 5
  ports:
  - containerPort: 8125
    hostPort: 8125
    name: dogstatsdport
    protocol: UDP
  volumes:
  - name: volume
    hostPath:
      path: /var/run/docker.sock
      type: ""
  volumeMounts:
  - mountPath: /var/run/docker.sock
    name: volume
    readOnly: true
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%

service:
  annotations:
    this_is: an_annotation
  type: ClusterIP
  labels: {}
  selector: {}
  ports:
  - name: dogstatsdport
    port: 8125
    protocol: TCP
    targetPort: 8125

secrets:
  the_password_is: shenanigans

configmaps:
- name: number-1-configmap-na
  data:
    key-1: |-
      This is a whole lot of data
      that can be translated to a configmap
    key-2: |-
      This is some other stuff
- name: number-2-configmap-na
  data:
    key-1: |-
      This is a whole lot of data
      that can be translated to a configmap
    key-2: |-
      This is some other stuff
