apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.annotations }}
  annotations:
    {{ toYaml .Values.service.annotations }}
  {{- end }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: Tiller
    release: {{ .Chart.Name }}
  name: {{ .Values.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  {{- if .Values.service.ports }}
  ports:
{{toYaml .Values.service.ports | indent 4 }}
  {{- end }}
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Chart.Name }}
  sessionAffinity: None
  type: {{ .Values.service.type }}
