{{- if .Values.service }}
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.annotations }}
  annotations:
    {{ toYaml .Values.service.annotations }}
  {{- end }}
  name: {{ .Values.name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  {{- if .Values.service.ports }}
  ports:
{{toYaml .Values.service.ports | indent 4 }}
  {{- end }}
  selector:
    app: {{ .Chart.Name }}
  sessionAffinity: None
  type: {{ .Values.service.type }}
{{- end }}
